- name: Update VPX to latest license
  become: yes
  remote_user: root
  hosts: localhost

  tasks:
    - name: Remove current license

    - name: Add new license

    - name: Get session token

    - name: Warm reboot the loadbalancer
